### ISSUE TITLE
failed linking file resources.

### ISSUE THREAD

**Issue by anvpn** [vhnguyen1001/android-circle-seekbar#1]
Hi there 

It only supports to API 27 and more ?

Is downgrade possible ?

I having following error comes 

Android resource linking failed
Output:  /Users/pc/Downloads/LocoKerala17SEPT2018 2/app/src/main/res/layout/radius_dialog.xml:78: error: attribute csb_indicatorIcon (aka com.locokerala.app:csb_indicatorIcon) not found.
/Users/pc/Downloads/LocoKerala17SEPT2018 2/app/src/main/res/layout/radius_dialog.xml:78: error: attribute csb_points (aka com.locokerala.app:csb_points) not found.
error: failed linking file resources.

Command: /Users/pc/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-osx.jar/22e993b74a5c184286defae89a72c810/aapt2-3.2.0-4818971-osx/aapt2 link -I\
        /Users/pc/Library/Android/sdk/platforms/android-27/android.jar\
        --manifest\
        /Users/pc/Downloads/LocoKerala17SEPT2018 2/app/build/intermediates/instant_run_merged_manifests/debug/processDebugManifest/instant-run/AndroidManifest.xml\
        -o\
        /Users/pc/Downloads/LocoKerala17SEPT2018 2/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/Users/pc/Downloads/LocoKerala17SEPT2018 2/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /Users/pc/Downloads/LocoKerala17SEPT2018 2/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        com.app\
        -0\
        apk\
        --preferred-density\
        xhdpi\

**Comment by vhnguyen1001** [comment]
Sorry @AnitaVPN , I forgot to update readme. attribute `csb_indicatorIcon` and `csb_points ` were removed. You should use new attributes in xml below: 

```
<hiennguyen.me.circleseekbar.CircleSeekBar
        android:id="@+id/circular"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:padding="64dp"
        app:csb_arcColor="@color/color_arc"
        app:csb_arcWidth="6dp"
        app:csb_thumbDrawable="@drawable/ic_circle_seekbar"
        app:csb_max="1000"
        app:csb_min="10"
        app:csb_progress="300"
        app:csb_progressColor="#00aad4"
        app:csb_progressWidth="12dp"
        app:csb_step="5"
        app:csb_textColor="@color/color_text"
        app:csb_textSize="36sp"
        app:csb_thumbSize="36dp"
        />
```

**Comment by anvpn** [comment]
Thanks for update

**Comment by asad191** [comment]
cant set progress at run time

**Comment by asad191** [comment]
> Sorry @AnitaVPN , I forgot to update readme. attribute `csb_indicatorIcon` and `csb_points ` were removed. You should use new attributes in xml below:
> 
> ```
> <hiennguyen.me.circleseekbar.CircleSeekBar
>         android:id="@+id/circular"
>         android:layout_width="0dp"
>         android:layout_height="0dp"
>         android:padding="64dp"
>         app:csb_arcColor="@color/color_arc"
>         app:csb_arcWidth="6dp"
>         app:csb_thumbDrawable="@drawable/ic_circle_seekbar"
>         app:csb_max="1000"
>         app:csb_min="10"
>         app:csb_progress="300"
>         app:csb_progressColor="#00aad4"
>         app:csb_progressWidth="12dp"
>         app:csb_step="5"
>         app:csb_textColor="@color/color_text"
>         app:csb_textSize="36sp"
>         app:csb_thumbSize="36dp"
>         />
> ```

can set progress at run time 

also not set text
